# Generated by Django 5.1.3 on 2026-01-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chunk_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='core_docume_project_598918_idx',
            old_name='doc_chunk_idx',
        ),
    ]
